---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sidecar-injector-webhook-certs
spec:
  secretName: sidecar-injector-webhook-certs
  dnsNames:
    - sidecar-injector-webhook.latency-agent-admin.svc
    - sidecar-injector-webhook.latency-agent-admin.svc.cluster.local
  issuerRef:
    name: selfsigned
