---
apiVersion: v1
kind: Service
metadata:
  name: sidecar-injector-webhook
spec:
  selector:
    app: sidecar-injector-webhook
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-injector-webhook-deployment
  labels:
    app: sidecar-injector-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-injector-webhook
  template:
    metadata:
      labels:
        app: sidecar-injector-webhook
    spec:
      containers:
        - name: injector-webhook
          image: "github.com/jayce-jia/tidb-latency-agent-mutating-webhook:0.1"
          ports:
            - containerPort: 443
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: health
              port: 443
            initialDelaySeconds: 1
            periodSeconds: 1
          command: ["./webhook"]
          args:
            - -sidecarSpecFile
            - spec/sidecar.yaml
            - -tlsCertFile
            - /etc/webhook/certs/tls.crt
            - -tlsKeyFile
            - /etc/webhook/certs/tls.key
            - -agentContainerName
            - latency-agent
            - -agentImage
            - github.com/jayce-jia/tidb-latency-agent-example
            - -agentImageTag
            - '0.1'
            - -agentManagementPort
            - '2332'
            - -agentInitLatency
            - 0s
            - -agentApplyPeriod
            - 1s
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: sidecar-injector-webhook-certs

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "sidecar-injector-webhook-configuration"
  annotations:
    cert-manager.io/inject-ca-from: latency-agent-admin/sidecar-injector-webhook-certs
webhooks:
  - name: "latency-agent.sidecar-injector.webhook"
    admissionReviewVersions: ["v1"]
    namespaceSelector:
      matchLabels:
        jayce.jia.latency.agent.sidecar-injector: enabled
    rules:
      - operations: ["CREATE"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["pods"]
    clientConfig:
      service:
        name: sidecar-injector-webhook
        namespace: latency-agent-admin
        port: 443
        path: /inject
    sideEffects: None
    timeoutSeconds: 5
